version: 2

jobs:
  build_js:
    docker:
      - image: emscripten/emsdk:2.0.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python3 --version && emcc --version && cmake --version
      - run: python3 src/build_javascript.py
      - persist_to_workspace:
          root: src/build/artifacts_js
          paths:
            - .
  deploy_js:
    docker:
      - image: circleci/python:2.7-jessie
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    environment:
      S3_BASE_URL: s3://files.na.mcneel.com/rhino3dm/js
    steps:
      - attach_workspace:
          at: src/build/artifacts_js
      - run: ls -l src/build/artifacts_js
      - run: python --version
      - run: sudo pip install awscli
        # upload artifacts to s3
      - run: aws s3 cp src/build/artifacts_js $S3_BASE_URL/dujour/$CIRCLE_BUILD_NUM/ --recursive --acl public-read
        # re-upload rhino3dm.wasm with mime-type "application/wasm"
      - run: aws s3 cp src/build/artifacts_js/rhino3dm.wasm $S3_BASE_URL/dujour/$CIRCLE_BUILD_NUM/ --acl public-read --content-type "application/wasm"
        # copy artifacts from dujour/$CIRCLE_BUILD_NUM/ to latest/
      - run:
          name: Copy artifacts to latest/
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 cp $S3_BASE_URL/dujour/$CIRCLE_BUILD_NUM/ $S3_BASE_URL/latest/ --recursive --acl public-read
            fi

  build_py2:
    docker:
      - image: mcneel/rhino3dm-dev:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python2 --version && cmake --version
      - run: python2 setup.py bdist_wheel

  build_py3:
    docker:
      - image: python:3.8-slim-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: apt update && apt install -yy git cmake gcc g++
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version
      - run: python3 setup.py bdist_wheel

  build_py3_mac:
    macos:
      xcode: "11.2.0"
    steps:
      # brew update required to workaround Homebrew/brew#5513
      - run: brew update
      - run: brew install cmake
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version
      - run: python3 setup.py bdist_wheel

  build_dotnet:
    docker:
      - image: mcneel/rhino3dm-dev:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version && dotnet --version
      - run: python3 script/bootstrap.py -p linux
      - run: python3 script/setup.py -p linux -v
      - run: python3 script/build.py -p linux -v

  build_dotnet_amzn2:
    docker:
      - image: mcneel/rhino3dm-dev-amzn2:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version && dotnet --version
      - run: python3 script/bootstrap.py -p linux
      - run: python3 script/setup.py -p linux -v
      - run: python3 script/build.py -p linux -v

workflows:
  version: 2
  build:
    jobs:
      - build_js:
          context:
            - docker-hub-creds
      # 2020-06-28: use jsdelivr instead of publishing to files.mcneel.com
      # - deploy_js:
      #     requires:
      #       - build_js
      - build_py2:
          context:
            - docker-hub-creds
      - build_py3:
          context:
            - docker-hub-creds
      - build_py3_mac:
          context:
            - docker-hub-creds
      - build_dotnet:
          context:
            - docker-hub-creds
      - build_dotnet_amzn2:
          context:
            - docker-hub-creds
