name: workflow release python pack
on: [workflow_dispatch]
jobs:

  build_py_manylinux2014:
    name: build python ${{ matrix.python-version }} manylinux2014
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: [cp38-cp38, cp39-cp39]
      fail-fast: false
    steps:
    - name: info
      run: /opt/python/${{ matrix.python-version }}/bin/python --version
    - name: checkout
      uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init
    - name: build python manylinux
      run: /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel
    - name: audit python wheel
      run: auditwheel repair dist/*.whl
    - name: list files
      run: ls -R
    - name: artifact name
      id: artifactname
      run: |
        cd wheelhouse
        echo "::set-output name=file::$(ls *.whl| head -1)"
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
        name: ${{ steps.artifactname.outputs.file }}

  pack_py:
    name: pack python
    needs: [build_py_manylinux2014]
    runs-on: ubuntu-latest
    steps:
      - name: download python artifacts dist
        uses: elonh/download-artifact-regexp@master
        with:
          pattern: .*whl(:|$).*
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: unzip files
        run: |
          mkdir output
          find dist -type f -print0 | xargs -0 mv -t output
          cd output
          ls
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          path: output
          name: rhino3dm.py all wheels
