name: workflow release python pack
on: [workflow_dispatch]
jobs:

  build_py_sdist:
    name: build python sdist
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
      - name: info
        run: python --version && cmake --version
      - name: install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: checkout
        uses: actions/checkout@v2
      - name: update submodules
        run: git submodule update --init
      - name: build python sdist
        run: python setup.py sdist
      - name: check sdist
        run: |
          # installs rhino3dm from the source distribution
          # into a virtualenv and tries to import it

          # set up directory
          rm -rf test_install
          mkdir test_install
          cd test_install

          # create virtualenv
          python -m venv venv
          . venv/bin/activate
          pip install wheel

          # install
          pip install --verbose ../dist/*.tar.gz

          # test
          python -c "import rhino3dm; print(rhino3dm.__version__)"
      - name: list files
        run: ls -R
      - name: artifact name
        id: artifactname
        run: |
          cd dist
          echo "::set-output name=file::$(ls *.tar.gz| head -1)"
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ${{ steps.artifactname.outputs.file }}

  build_py_manylinux2014:
    name: build python ${{ matrix.python-version }} manylinux2014
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      matrix:
        python-version: [cp38-cp38, cp39-cp39]
      fail-fast: false
    steps:
    - name: info
      run: /opt/python/${{ matrix.python-version }}/bin/python --version
    - name: checkout
      uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init
    - name: build python manylinux
      run: /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel
    - name: audit python wheel
      run: auditwheel repair dist/*.whl
    - name: list files
      run: ls -R
    - name: artifact name
      id: artifactname
      run: |
        cd wheelhouse
        echo "::set-output name=file::$(ls *.whl| head -1)"
    - name: artifacts
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
        name: ${{ steps.artifactname.outputs.file }}

  build_py_all_bdist:
    name: build python ${{ matrix.python-version }} ${{ matrix.target }} bdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]
        python-version: [2.7, 3.7, 3.8, 3.9, '3.10']
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-11
            target: macos
      fail-fast: false
    steps:
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: info
        run: python --version && cmake --version
      - name: install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: checkout
        uses: actions/checkout@v2
      - name: update submodules
        run: git submodule update --init
      - name: build python ${{ matrix.python-version }} ${{ matrix.os }}
        run: python setup.py bdist_wheel
      - name: code-sign native libraries
        env:
          IDENTITY_ID: ${{ secrets.IDENTITY_ID }}
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_KEYCHAIN_TEMP_PWD: ${{ secrets.MACOS_KEYCHAIN_TEMP_PWD }}
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            ./script/codesign-native.sh src/build
          else
            echo "$RUNNER_OS not supported for code-signing"
            exit 0
          fi
        shell: bash
      - name: list files
        run: ls -R
      - name: artifact name
        id: artifactname
        shell: bash
        run: |
          cd dist
          echo "::set-output name=file::$(ls *.whl| head -1)"
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist
          name: ${{ steps.artifactname.outputs.file }}

  pack_py:
    name: pack python
    needs: [build_py_manylinux2014, build_py_all_bdist, build_py_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: download python artifacts dist
        uses: elonh/download-artifact-regexp@master
        with:
          pattern: ^.*\.(whl|tar.gz)$ #.*whl(:|$).* 
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: unzip files
        run: |
          mkdir output
          find dist -type f -print0 | xargs -0 mv -t output
          cd output
          ls
          unzip '*.whl'
          ls -R
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          path: output
          name: rhino3dm.py all wheels
