# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow ci docgen tmp
on: [push, pull_request]

env:
  RETENTION_DAYS: 15

jobs:
  build_js:
    name: build docgen
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.30
    steps:
      - name: info
        run: python3 --version && emcc --version && cmake --version
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: safe dir
        run: git config --system --add safe.directory /__w/rhino3dm/rhino3dm
      - name: update submodules
        run: git submodule update --init
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: docgen
        shell: bash
        run: |
          dotnet build src/docgen
          cd src/docgen/bin/Debug
          ./docgen
          cd ../../../../
          cp src/docgen/out/js_tsdef/rhino3dm.d.ts src/build/javascript/artifacts_js
          ls
          