# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow ci arm64 linux
on: [push, pull_request]


env:
  RETENTION_DAYS: 15

jobs:

  build_dotnet:
    name: build dotnet
    runs-on: ubuntu-latest
    steps:
      - name: setup environment
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register
          apt-get install qemu binfmt-support qemu-user-static
          docker run -v $(pwd)/qemu-aarch64-static:/usr/bin/qemu-aarch64-static -it mcneel/rhino3dm-v-arm64 bash
          uname -a
          ls
      - name: info
        run: python3 --version && cmake --version && dotnet --version && git --version
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: safe directory
        run: git config --global --add safe.directory /__w/rhino3dm/rhino3dm
      - name: update submodules
        run: ls && git submodule update --init
      - name: bootstrap
        run: python3 script/bootstrap.py -p linux
      - name: setup
        run: python3 script/setup.py -p linux -v -l
      - name: build dotnet
        run: python3 script/build.py -p linux -v -l
      - name: artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          path: |
            src/build/linux/librhino3dm_native.so
          name: rhino3dm.net arm64
          retention-days: ${{ env.RETENTION_DAYS }}
