# for a list of available software on the different virtual environments, please see:
# https://github.com/actions/virtual-environments/tree/main/images

name: workflow ci js tmp
on: [push, pull_request]

env:
  RETENTION_DAYS: 15

jobs:
  build_js:
    name: build rhino3dm.js
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.30
    steps:
      - name: info
        run: python3 --version && emcc --version && cmake --version
      - name: checkout
        uses: actions/checkout@v2
      - name: safe dir
        run: git config --system --add safe.directory /__w/rhino3dm/rhino3dm
      - name: update submodules
        run: git submodule update --init
      - name: bootstrap
        run: python3 script/bootstrap.py -p js
      - name: setup
        run: python3 script/setup.py -p js -o -v
      - name: build js
        run: python3 script/build.py -p js -o -v
      - name: minify
        uses: actions/webpreprocessor@v1.13
        with:
          dir: src/build/javascript/artifacts_js
          action: uglifyjs
          filename: rhino3dm.js
      - name: minify module
        uses: actions/webpreprocessor@v1.13
        with:
          dir: src/build/javascript/artifacts_js
          action: uglifyjs
          filename: rhino3dm.module.js
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          path: src/build/javascript/artifacts_js
          name: rhino3dm.js
          retention-days: ${{ env.RETENTION_DAYS }}